---
name: Build Image without pushing
on:
  workflow_call:
jobs:
  build-image:
    runs-on: ubuntu-latest
    container: jsfillman/kb-sdk
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "kbase.yml, Makefile, *.spec"

      - name: Run kb-sdk compile
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          cd $GITHUB_WORKSPACE;
          if [ -f kbase.yml ] && [ -f Makefile ] && [ -f *.spec ] ; then
            make compile;
          else
            echo "Not a kb-sdk dependent app, skipping."
          fi

      - name: Build without push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: false
